### ISSUE TITLE
What is the plan for CSpydr.

### ISSUE THREAD

**Issue by Ishimachi** [Spydr06/CSpydr#23]
Hello.
Firstly, congratulations on developing such an appealing language.

My question is rather straightforward, I suppose: What is the plan for CSpydr? What are its goals? What does it aim to achieve and what issues does it seek to mitigate?

As the creator, how far do you intend to take your creation?

Thank you, and best wishes. I certainly look forward to exploring the language further.

**Comment by Spydr06** [comment]
Hi, 
first of all, thanks for your interest :)

> What is the plan for CSpydr? What are its goals? What does it aim to achieve and what issues does it seek to mitigate?

There aren't any "goals" I want to achieve or "problems" to solve with this project. It's mainly for my own education and because I enjoy writing code/working on it otherwise. I suppose it's an expression of what the "perfect language" would look like for me.

> As the creator, how far do you intend to take your creation?

Honestly, I don't know. I'll continue to work on this as long as it's enjoyable for me... I'm also interested in other topics, like OS-dev, so I plan to use this language as the native language for a little toy OS for example.

But, as I said a few times before, I won't just "stop" writing code for it just yet. This project is over 3 years old now, so it has been around for the better part of my programming career and I'll not just "let go" of it. :D

**Comment by Ishimachi** [comment]
Being reassured that the project won't die is very reassuring indeed. It's common to see programming languages fade away rather quickly, so I hope your progress continues.

Have you considered creating a website where all documentation would reside, making it much easier to access information about the language? This could include providing examples such as C interop, generics, and an overall overview of the language.

**Comment by Spydr06** [comment]
> Have you considered creating a website where all documentation would reside, making it much easier to access information about the language? This could include providing examples such as C interop, generics, and an overall overview of the language.

I have, yes, but web development is neither exactly one of my strengths nor particularly interesting for me. I quite like GitHub's [Wiki tab](https://github.com/Spydr06/CSpydr/wiki). Please note that the docs there are neither complete nor up-to-date.

The best resources for learning about CSpydr currently are its standard library found in [`src/std`](https://github.com/Spydr06/CSpydr/tree/main/src/std) and the language [examples](https://github.com/Spydr06/CSpydr/tree/main/examples).

**Comment by Ishimachi** [comment]
I see, thank you. If that's the case, it's understandable.

Will there be macOS and Windows support coming soon? macOS has all the dependencies needed to support this, I believe.

**Comment by Spydr06** [comment]
I had planned windows support long ago, but it gave me _so_ much trouble that I never continued with it (C on windows sucks :/).

MacOS should be easier, but I don't have a Mac to try stuff out and MacOS in a VM is just plain unusable sadly.

Every new OS would also require a complete re-implementation of the stdlib, since it's very closely bound to the linux syscalls.

**Comment by Ishimachi** [comment]
While I've closed it, I just wanted to say that I hope we end up having a macOS version at some point. I rarely use my laptop and would love to transition to using CSpydr on my Mac Studio.

Godspeed, have nice faith in this language, even if its a personal project.
Who knows how far it can go, maybe even one day you will have WASM support.

**Comment by Spydr06** [comment]
There won't be any macOS support unless someone other than me implements it sadly. I do not plan getting a Mac anytime soon :/

**Comment by Ishimachi** [comment]
I don't know how useful this could be but recently found this:
https://www.youtube.com/watch?v=Qa6y_CiyAMA

Perhaps it could work well for you?
